name: 每日签到Luogu

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 发送签到请求
      run: |
        curl -s -X POST \
          -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.60"\
          -H "Cookie: __client_id=93cd6464e4301df3b45d2af6f1ff91e6ee540409; C3VK=0c6a02; _uid=1614908" \
          -H "Accept: */*" \
          -H "Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2" \
          -H "Accept-Encoding: gzip, deflate, br" \
          -H "Connection: keep-alive" \
          -H "Referer: https://www.luogu.com.cn/" \
          -H "Cache-Control: no-cache" \
          https://www.luogu.com.cn/index/ajax_punch
