
name: cpu充电

on:
  schedule:
    - cron: '0 12 * * 2,4,6'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 发送签到请求
      run: |
        curl --location --request POST 'https://api.v2.rainyun.com/product/rgs//cpu-charge' \
             --header 'x-api-key: ${{ secrets.RAINYUN_API_KEY }}' \
             --header 'Content-Type: application/json' \
             --data-raw '{
                "mode": "point",
                "points": 400
             }'
